### ISSUE TITLE
[bug][2.1.5] Sometimes on app installation special dropdown input are text input

### ISSUE THREAD

**Issue by zamentur** [YunoHost/yunohost-admin#97] opened 2015-05-08 22:56 UTC
Hi,

On yunohost-admin/testing 2.1.5, sometimes I have a dropdown input (list of users or domains) replaced by a text input.
Maxime says that he got pages with dropdown and pages with text input with the same app, so same manifest...

Thanks for this new version.

**Comment by opi** [comment] 2015-07-09 07:24
I saw that behavior sometimes too. 

Text input to select list transform is done here : https://github.com/YunoHost/yunohost-admin/blob/unstable/src%2Fjs%2Fapp.js#L1058 , and the variable `params.domains` is filled by a before filter during https://github.com/YunoHost/yunohost-admin/blob/unstable/src%2Fjs%2Fapp.js#L348

I guess sometimes the request during before filter is too long, and sammy.js do not wait enough.

**Comment by opi** [comment] 2015-07-09 07:26
When you have this bug, do you have the help link below text input ? ("manage users", "manage domains")

Help links are added during https://github.com/YunoHost/yunohost-admin/blob/unstable/src%2Fjs%2Fapp.js#L1083 , it could help debugging to know if they were here.

**Comment by alexAubin** [comment] 2017-03-26 20:15
Duplicate of https://dev.yunohost.org/issues/43

**Closed by alexAubin** 2017-03-26 20:15 UTC
