### ISSUE TITLE
Improve translation system

### ISSUE THREAD

**Issue by opi** [YunoHost/yunohost-admin#88] opened 2015-02-20 13:26 UTC
By using an equivalent to Python str.format()

See https://stackoverflow.com/questions/13639464/javascript-equivalent-to-pythons-format & https://github.com/xfix/python-format

**Comment by alexAubin** [comment] 2017-03-26 20:10
Duplicate of https://dev.yunohost.org/issues/788 I think

**Closed by alexAubin** 2017-03-26 20:10 UTC
Labels: enhancement
